const { log } = require("console")
const fs= require("fs")
fs.writeFileSync("write.txt","I am from india.")
//fs.writeFile("write.txt","I am from india.")
r=fs.readFileSync("write.txt" ,"utf8")
console.log(r);
//fs.writeFileSync("write.html","I am html file.")
//fs.writeFileSync("write2.html","I am html file.")
//fs.unlinkSync("write.html")
//fs.unlinkSync("write2.html")
//fs.unlinkSync("write.txt")
fs.appendFileSync("write.txt" , " keep practicing")
